# Generated by Django 4.2 on 2024-04-22 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artfight_app', '0003_duel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duel',
            name='art',
        ),
        migrations.AddField(
            model_name='duel',
            name='artOne',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artOne', to='artfight_app.individualart'),
        ),
        migrations.AddField(
            model_name='duel',
            name='artTwo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artTwo', to='artfight_app.individualart'),
        ),
    ]
