# Generated by Django 4.2 on 2024-04-22 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artfight_app', '0005_remove_permission_module_alter_individualart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='artOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artOne', to='artfight_app.individualart'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='artTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='artTwo', to='artfight_app.individualart'),
        ),
    ]
